"""The Vocab Challenger curriculum, generated once from vocab-app's server/curriculum.ts.

A word's id is its index, and saved wordbooks store it, so never reorder or remove
entries: append new words at the end. Server-only: options[0] is the correct usage and
reasons line up with options, so nothing here may reach a client before a round resolves.
"""

from dataclasses import dataclass
from typing import Literal

Difficulty = Literal["Foundation", "Intermediate", "Advanced"]


@dataclass(frozen=True)
class VocabWord:
    id: int
    word: str
    pos: str
    definition: str
    difficulty: Difficulty
    # The scenario shown above the usage question.
    prompt: str
    # Four sentences using the word; options[0] is the one that uses it correctly.
    options: tuple[str, ...]
    # Why each option is right or wrong, aligned with options.
    reasons: tuple[str, ...]
    example: str
    synonyms: str
    nuance: str
    # Words the context question offers as distractors, when they're in the curriculum.
    alternatives: tuple[str, ...]


WORDS: tuple[VocabWord, ...] = (
    VocabWord(
        id=0,
        word="discerning",
        pos="adjective",
        definition="Showing good judgment and an ability to notice subtle differences.",
        difficulty="Foundation",
        prompt="An editor is choosing which essays to publish.",
        options=(
            "The discerning editor distinguished an original argument from a merely fashionable one.",
            "The discerning editor accepted every essay without reading it.",
            "The discerning editor could not tell an argument from an anecdote.",
            "The discerning editor printed the essays in alphabetical order.",
        ),
        reasons=(
            "Careful discrimination between quality and appearance shows good judgment.",
            "Accepting everything without examination shows no discrimination.",
            "Failing to notice an important distinction is the opposite of discernment.",
            "Alphabetical organization says nothing about judgment.",
        ),
        example="A discerning listener hears the tension beneath a polite reply.",
        synonyms="perceptive, judicious",
        nuance="Discernment implies judgment, not merely sharp eyesight.",
        alternatives=(),
    ),
    VocabWord(
        id=1,
        word="equivocal",
        pos="adjective",
        definition="Ambiguous or open to more than one interpretation.",
        difficulty="Intermediate",
        prompt="The statement leaves it unclear whether the committee supports the proposal.",
        options=(
            "The committee offered an equivocal response that could be read as approval or refusal.",
            "The committee gave an equivocal refusal, making its opposition unmistakable.",
            "Both candidates earned an equivocal number of votes: exactly 200 each.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: ambiguous or open to more than one interpretation.",
            "An unmistakable refusal is unambiguous, the opposite of equivocal.",
            "Equal quantities are equivalent or equal, not equivocal.",
        ),
        example="The test produced equivocal evidence, so the investigators collected another sample.",
        synonyms="ambiguous, inconclusive, unclear",
        nuance="Equivocal describes ambiguity; ambivalent describes mixed feelings.",
        alternatives=(
            "ambivalent",
            "unequivocal",
        ),
    ),
    VocabWord(
        id=2,
        word="pragmatic",
        pos="adjective",
        definition="Concerned with practical outcomes rather than abstract ideals.",
        difficulty="Foundation",
        prompt="A team adopts a workable compromise instead of pursuing a perfect but impossible plan.",
        options=(
            "She took a pragmatic approach, choosing the repair they could afford today.",
            "He was pragmatic because he followed his principles regardless of the consequences.",
            "The proposal was pragmatic because it was explained in exceptionally clear prose.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: concerned with practical outcomes rather than abstract ideals.",
            "Following ideals regardless of results is not evidence of practical judgment.",
            "Clear expression is lucid; it does not establish practicality.",
        ),
        example="A pragmatic timetable allowed for delays rather than assuming perfect conditions.",
        synonyms="practical, realistic, workable",
        nuance="A pragmatic choice can be principled; the emphasis is on what works in the situation.",
        alternatives=(
            "dogmatic",
            "lucid",
        ),
    ),
    VocabWord(
        id=3,
        word="reticent",
        pos="adjective",
        definition="Reluctant to speak or reveal one's thoughts.",
        difficulty="Intermediate",
        prompt="A colleague remains quiet about a sensitive personal subject.",
        options=(
            "Usually talkative, he became reticent when asked about his family.",
            "She was reticent about the plan, explaining her reservations at great length.",
            "The reticent runner hesitated to enter the race but freely discussed all his thoughts.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: reluctant to speak or reveal one's thoughts.",
            "Openly explaining reservations at length is not being reserved in speech.",
            "Reluctance to act alone is not reticence; the core meaning concerns speaking.",
        ),
        example="The author was reticent about the experiences behind the novel.",
        synonyms="reserved, uncommunicative, restrained",
        nuance="Prefer reluctant for unwillingness to act; reticent precisely describes restraint in disclosure.",
        alternatives=(
            "laconic",
            "ambivalent",
        ),
    ),
    VocabWord(
        id=4,
        word="salient",
        pos="adjective",
        definition="Most noticeable or important in a particular context.",
        difficulty="Intermediate",
        prompt="A briefing highlights the facts that matter most to the decision.",
        options=(
            "She summarized the salient findings before discussing minor details.",
            "Every incidental detail was equally salient, with nothing standing out.",
            "The findings were salient because they had remained hidden for years.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: most noticeable or important in a particular context.",
            "Salience distinguishes what stands out from incidental details.",
            "Being hidden is not being noticeable or prominent.",
        ),
        example="The most salient difference between the plans was their ongoing cost.",
        synonyms="prominent, notable, key",
        nuance="Salient is context-dependent: a fact can be salient for one decision and irrelevant to another.",
        alternatives=(
            "incidental",
            "latent",
        ),
    ),
    VocabWord(
        id=5,
        word="mitigate",
        pos="verb",
        definition="Make something harmful, severe, or painful less serious.",
        difficulty="Foundation",
        prompt="A town cannot stop a flood but can reduce the damage it causes.",
        options=(
            "The new barriers helped mitigate the damage from seasonal flooding.",
            "The barriers mitigated the river, making it vanish completely.",
            "The committee mitigated the report by explaining every technical term.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: make something harmful, severe, or painful less serious.",
            "Mitigate means lessen severity, not eliminate a thing entirely.",
            "Clarifying language elucidates a report; it does not necessarily reduce harm.",
        ),
        example="Additional ventilation can mitigate the effects of indoor heat.",
        synonyms="lessen, alleviate, moderate",
        nuance="Mitigate usually takes a harm, risk, or adverse effect as its object.",
        alternatives=(
            "elucidate",
            "exacerbate",
        ),
    ),
    VocabWord(
        id=6,
        word="ephemeral",
        pos="adjective",
        definition="Lasting for a very short time.",
        difficulty="Foundation",
        prompt="A brief burst of attention disappears almost as soon as it arrives.",
        options=(
            "The campaign enjoyed ephemeral fame before the public moved on a week later.",
            "Her ephemeral influence persisted steadily across several generations.",
            "The ephemeral painting was difficult to interpret because its symbols were obscure.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: lasting for a very short time.",
            "Influence lasting generations is enduring, not ephemeral.",
            "Obscurity concerns understanding, not duration.",
        ),
        example="The frost formed an ephemeral pattern that disappeared in the morning sun.",
        synonyms="fleeting, transient, short-lived",
        nuance="Ephemeral describes short duration, not low importance or poor quality.",
        alternatives=(
            "enduring",
            "esoteric",
        ),
    ),
    VocabWord(
        id=7,
        word="cogent",
        pos="adjective",
        definition="Clear, logical, and convincing.",
        difficulty="Intermediate",
        prompt="A researcher makes a persuasive case using evidence and sound reasoning.",
        options=(
            "She offered a cogent argument supported by relevant evidence and a clear chain of reasoning.",
            "His cogent speech relied on emotional appeals that concealed contradictions.",
            "The cogent summary was short, though its reasoning was difficult to follow.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: clear, logical, and convincing.",
            "Emotional force cannot substitute for the logical clarity implied by cogent.",
            "Brevity alone does not make reasoning clear and convincing.",
        ),
        example="The lawyer gave a cogent explanation of how the records contradicted the claim.",
        synonyms="convincing, compelling, sound",
        nuance="Cogent is strongest for arguments, reasons, and explanations with persuasive logic.",
        alternatives=(
            "specious",
            "laconic",
        ),
    ),
    VocabWord(
        id=8,
        word="ambivalent",
        pos="adjective",
        definition="Having mixed or conflicting feelings about something.",
        difficulty="Intermediate",
        prompt="Someone welcomes a promotion but regrets having to leave a close team.",
        options=(
            "She felt ambivalent about the promotion: excited by the role but sad to leave her colleagues.",
            "She was ambivalent about the promotion because she had never heard about it.",
            "The announcement was ambivalent because its wording allowed two interpretations.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: having mixed or conflicting feelings about something.",
            "Lack of knowledge is not conflicting feelings.",
            "Ambiguous wording is equivocal; ambivalent describes attitudes or feelings.",
        ),
        example="He remained ambivalent about moving abroad despite the appealing job offer.",
        synonyms="conflicted, torn, uncertain",
        nuance="Ambivalence involves competing reactions, rather than mere indifference.",
        alternatives=(
            "equivocal",
            "indifferent",
        ),
    ),
    VocabWord(
        id=9,
        word="assiduous",
        pos="adjective",
        definition="Showing sustained care, effort, and diligence.",
        difficulty="Advanced",
        prompt="An archivist reconstructs a damaged record.",
        options=(
            "Her assiduous research involved months of careful cross-checking.",
            "Her assiduous research consisted of a careless guess.",
            "The assiduous archivist abandoned the task at the first difficulty.",
            "Assiduous research meant that the subject was easy.",
        ),
        reasons=(
            "Sustained, careful effort shows diligence.",
            "A careless guess lacks effort and care.",
            "Immediate abandonment does not show persistence.",
            "Assiduous describes effort, not task difficulty.",
        ),
        example="Assiduous preparation made the complex hearing manageable.",
        synonyms="diligent, painstaking",
        nuance="Assiduous emphasizes sustained application rather than innate talent.",
        alternatives=(),
    ),
    VocabWord(
        id=10,
        word="lucid",
        pos="adjective",
        definition="Clear and easy to understand; also mentally clear.",
        difficulty="Foundation",
        prompt="A lecturer explains a complex model.",
        options=(
            "Her lucid explanation made the unfamiliar model easy to follow.",
            "Her lucid explanation was impossible to understand.",
            "Her lucid explanation used contradictions to obscure the point.",
            "Her explanation was lucid because the room was brightly lit.",
        ),
        reasons=(
            "Clarity and intelligibility illustrate lucid expression.",
            "Incomprehensibility contradicts lucidity.",
            "Obscurity is the opposite of clarity.",
            "Room lighting does not establish clarity of thought.",
        ),
        example="During a lucid interval, he recognized the visitors.",
        synonyms="clear, intelligible",
        nuance="Lucid can describe expression or a state of mental clarity.",
        alternatives=(),
    ),
    VocabWord(
        id=11,
        word="intractable",
        pos="adjective",
        definition="Difficult to control, manage, or solve.",
        difficulty="Advanced",
        prompt="Negotiators face a persistent dispute.",
        options=(
            "The intractable dispute resisted every proposed compromise.",
            "The intractable dispute was easily settled in seconds.",
            "The problem was intractable because everyone readily agreed.",
            "Intractable meant the dispute had never begun.",
        ),
        reasons=(
            "Resistance to resolution illustrates an intractable problem.",
            "Easy resolution contradicts difficulty.",
            "Ready agreement does not illustrate resistance.",
            "Intractability concerns manageability, not existence.",
        ),
        example="The team confronted an intractable software defect.",
        synonyms="stubborn, unmanageable",
        nuance="Intractable can describe people, conditions, or problems.",
        alternatives=(),
    ),
    VocabWord(
        id=12,
        word="ubiquitous",
        pos="adjective",
        definition="Present or found everywhere, or very widely.",
        difficulty="Foundation",
        prompt="A device has become a familiar sight across nearly every workplace.",
        options=(
            "Smartphones have become ubiquitous in everyday life.",
            "The ubiquitous manuscript survives in just one private collection.",
            "The ubiquitous device was unusually expensive.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: present or found everywhere, or very widely.",
            "A single rare instance is not widespread.",
            "Price does not establish how widely something is found.",
        ),
        example="Contactless payment terminals are now ubiquitous in the city.",
        synonyms="omnipresent, pervasive, widespread",
        nuance="Ubiquitous is often used comparatively; it need not mean literally every place.",
        alternatives=(
            "scarce",
            "esoteric",
        ),
    ),
    VocabWord(
        id=13,
        word="obviate",
        pos="verb",
        definition="Remove a need or prevent a difficulty from arising.",
        difficulty="Advanced",
        prompt="A team automates a repetitive check.",
        options=(
            "Automation can obviate the need for daily manual checks.",
            "Automation obviated the need by making manual checks mandatory.",
            "The new process obviated work by doubling the required effort.",
            "Obviate meant to describe the check in more detail.",
        ),
        reasons=(
            "Removing the need for manual work illustrates obviate.",
            "Making checks mandatory creates a need.",
            "Doubling required work does not remove it.",
            "Description is not prevention or removal of a need.",
        ),
        example="A clear agreement obviated further debate.",
        synonyms="preclude, forestall",
        nuance="Often use “obviate the need for,” rather than “obviate against.”",
        alternatives=(),
    ),
    VocabWord(
        id=14,
        word="prosaic",
        pos="adjective",
        definition="Ordinary or lacking imagination and poetic beauty.",
        difficulty="Intermediate",
        prompt="The mystery turns out to have a mundane explanation.",
        options=(
            "The missing lights had a prosaic explanation: someone had unplugged the cable.",
            "The prosaic explanation involved a startling, imaginative vision of another world.",
            "The explanation was prosaic simply because it appeared in prose rather than verse.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: ordinary or lacking imagination and poetic beauty.",
            "A startling imaginative vision is not mundane.",
            "Writing in prose does not necessarily make its content dull or ordinary.",
        ),
        example="The trip ended for the prosaic reason that their car needed repairs.",
        synonyms="mundane, ordinary, unimaginative",
        nuance="Prosaic evaluates the character of something, not merely its literary format.",
        alternatives=(
            "novel",
            "esoteric",
        ),
    ),
    VocabWord(
        id=15,
        word="fastidious",
        pos="adjective",
        definition="Very attentive to detail and hard to please about standards.",
        difficulty="Intermediate",
        prompt="An editor insists that every citation follow the style guide exactly.",
        options=(
            "The fastidious editor checked every reference and rejected even minor inconsistencies.",
            "The fastidious editor finished quickly by ignoring small inconsistencies.",
            "His fastidious response arrived sooner than anyone expected.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: very attentive to detail and hard to please about standards.",
            "Ignoring details conflicts with exacting standards.",
            "Fastidious is not related to being fast.",
        ),
        example="A fastidious host polished every glass before the guests arrived.",
        synonyms="meticulous, exacting, particular",
        nuance="Fastidious can imply demanding standards, especially of cleanliness, taste, or accuracy.",
        alternatives=(
            "pragmatic",
            "expeditious",
        ),
    ),
    VocabWord(
        id=16,
        word="laconic",
        pos="adjective",
        definition="Using very few words.",
        difficulty="Intermediate",
        prompt="A witness replies briefly, with no elaboration.",
        options=(
            "Asked to describe the evening, the laconic witness replied, “Uneventful.”",
            "The laconic witness spoke for an hour but used simple vocabulary.",
            "Her laconic answer carefully avoided revealing her real opinion.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: using very few words.",
            "Simple words do not make a lengthy answer laconic.",
            "Avoiding commitment is evasive or equivocal; the answer may still be long.",
        ),
        example="His laconic review consisted of two words: “Worth reading.”",
        synonyms="terse, concise, brief",
        nuance="Laconic suggests a noticeably sparing manner of speech, sometimes dry or blunt.",
        alternatives=(
            "equivocal",
            "eloquent",
        ),
    ),
    VocabWord(
        id=17,
        word="magnanimous",
        pos="adjective",
        definition="Generous and forgiving, especially toward a rival or weaker person.",
        difficulty="Advanced",
        prompt="A winner responds to a rival's criticism.",
        options=(
            "Magnanimous in victory, she praised her rival and dismissed the insult.",
            "Magnanimous in victory, she humiliated her rival repeatedly.",
            "Her magnanimous gesture was an act of petty revenge.",
            "She was magnanimous because she won by a large margin.",
        ),
        reasons=(
            "Grace and generosity toward a rival show magnanimity.",
            "Humiliation is ungenerous.",
            "Petty revenge contradicts forgiving generosity.",
            "The size of a victory does not establish character.",
        ),
        example="He made a magnanimous offer to forgive the debt.",
        synonyms="generous, gracious",
        nuance="Magnanimous emphasizes nobility of spirit, not physical size.",
        alternatives=(),
    ),
    VocabWord(
        id=18,
        word="perfunctory",
        pos="adjective",
        definition="Done routinely with little care or interest.",
        difficulty="Advanced",
        prompt="A supervisor signs off on a report.",
        options=(
            "His perfunctory review consisted of a quick glance before signing.",
            "His perfunctory review involved weeks of meticulous scrutiny.",
            "He gave the report a perfunctory review with intense curiosity and care.",
            "The review was perfunctory because it reached the right conclusion.",
        ),
        reasons=(
            "A token glance shows little investment in the task.",
            "Meticulous scrutiny is not cursory.",
            "Intense care contradicts perfunctory performance.",
            "Correctness alone does not indicate care or its absence.",
        ),
        example="She offered a perfunctory greeting and returned to work.",
        synonyms="cursory, mechanical",
        nuance="Perfunctory suggests going through the motions, not simply being efficient.",
        alternatives=(),
    ),
    VocabWord(
        id=19,
        word="ostensible",
        pos="adjective",
        definition="Stated or appearing to be true, though possibly concealing something else.",
        difficulty="Advanced",
        prompt="A visit is officially for research, but its real purpose may be political.",
        options=(
            "The ostensible purpose of the visit was research, though the private meetings suggested otherwise.",
            "The ostensible purpose was the proven motive revealed after a full investigation.",
            "The ostensible purpose was impossible to determine because none had been stated or appeared.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: stated or appearing to be true, though possibly concealing something else.",
            "Ostensible refers to the apparent or professed purpose, not necessarily the proven real one.",
            "There must be an apparent or professed basis for describing something as ostensible.",
        ),
        example="His ostensible concern was cost, but he kept returning to questions of control.",
        synonyms="apparent, professed, purported",
        nuance="Ostensible leaves room for a different underlying reality; it does not prove deception.",
        alternatives=(
            "latent",
            "unequivocal",
        ),
    ),
    VocabWord(
        id=20,
        word="anomalous",
        pos="adjective",
        definition="Deviating from what is standard, normal, or expected.",
        difficulty="Advanced",
        prompt="A scientist checks an unusual measurement.",
        options=(
            "The anomalous reading differed sharply from every previous result.",
            "The anomalous reading exactly matched the expected pattern.",
            "The reading was anomalous because it was typical.",
            "Anomalous meant the scientist disliked the reading.",
        ),
        reasons=(
            "Departure from the established pattern is anomalous.",
            "Matching expectations is not deviation.",
            "Typical behavior contradicts anomalous behavior.",
            "A personal preference does not establish an anomaly.",
        ),
        example="One anomalous vote interrupted the unanimous pattern.",
        synonyms="irregular, atypical",
        nuance="Anomalous describes deviation and does not itself explain the cause.",
        alternatives=(),
    ),
    VocabWord(
        id=21,
        word="tenuous",
        pos="adjective",
        definition="Weak, slight, or lacking a solid basis.",
        difficulty="Intermediate",
        prompt="A theory rests on evidence with only a weak connection to the conclusion.",
        options=(
            "The connection between the two events was tenuous and supported by little evidence.",
            "The tenuous evidence conclusively settled the question.",
            "The discussion was tenuous because it continued for three hours.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: weak, slight, or lacking a solid basis.",
            "Conclusive evidence is strong, not tenuous.",
            "Duration does not establish weakness or lack of substance.",
        ),
        example="Her claim to ownership rested on a tenuous interpretation of an unsigned note.",
        synonyms="weak, slight, flimsy",
        nuance="Tenuous often describes connections, claims, or positions that may not hold up.",
        alternatives=(
            "cogent",
            "protracted",
        ),
    ),
    VocabWord(
        id=22,
        word="veracity",
        pos="noun",
        definition="Truthfulness or accuracy.",
        difficulty="Advanced",
        prompt="A journalist verifies a source's account.",
        options=(
            "She checked independent records to establish the account's veracity.",
            "She established its veracity by showing every claim was false.",
            "The account's veracity referred to how hungry the source was.",
            "Veracity meant the story was entertaining regardless of truth.",
        ),
        reasons=(
            "Records help test whether an account is true.",
            "Falsehood contradicts veracity.",
            "Hunger is associated with voracity, not veracity.",
            "Entertainment value is separate from truth.",
        ),
        example="The contradictory dates cast doubt on his veracity.",
        synonyms="truthfulness, accuracy",
        nuance="Do not confuse veracity with voracity, an intense appetite.",
        alternatives=(),
    ),
    VocabWord(
        id=23,
        word="sanguine",
        pos="adjective",
        definition="Optimistic or hopeful, especially despite difficulty.",
        difficulty="Advanced",
        prompt="A founder remains hopeful even after an early setback.",
        options=(
            "Despite the failed trial, she remained sanguine about the next attempt.",
            "He was sanguine about the project, expecting disaster at every stage.",
            "The sanguine director became furious and shouted at the whole team.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: optimistic or hopeful, especially despite difficulty.",
            "Expecting disaster is pessimistic, not optimistic.",
            "Anger does not establish the hopeful outlook intended in this sense.",
        ),
        example="The analysts were sanguine about recovery despite the weak quarter.",
        synonyms="optimistic, hopeful, confident",
        nuance="In its common figurative sense, sanguine describes outlook, not calmness or certainty of success.",
        alternatives=(
            "ambivalent",
            "reticent",
        ),
    ),
    VocabWord(
        id=24,
        word="circumspect",
        pos="adjective",
        definition="Cautious and attentive to possible risks or consequences.",
        difficulty="Advanced",
        prompt="A diplomat discusses an unresolved conflict.",
        options=(
            "She was circumspect, weighing the consequences of each public statement.",
            "She was circumspect, speaking recklessly without considering consequences.",
            "The circumspect diplomat disclosed every secret on impulse.",
            "Circumspect meant that she stood in a circle.",
        ),
        reasons=(
            "Deliberate caution about consequences shows circumspection.",
            "Recklessness contradicts caution.",
            "Impulsive disclosure ignores risks.",
            "The word describes judgment, not physical position.",
        ),
        example="Investors took a circumspect approach to the untested market.",
        synonyms="cautious, prudent",
        nuance="Circumspect emphasizes looking at risks before acting.",
        alternatives=(),
    ),
    VocabWord(
        id=25,
        word="esoteric",
        pos="adjective",
        definition="Understood by or intended for a small group with specialized knowledge.",
        difficulty="Intermediate",
        prompt="A discussion assumes knowledge of a specialized branch of mathematics.",
        options=(
            "The lecture explored esoteric notation familiar only to specialists in the field.",
            "The esoteric lecture explained everyday facts that everyone already understood.",
            "The esoteric lecture was brief enough to fit into five minutes.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: understood by or intended for a small group with specialized knowledge.",
            "Widely understood everyday facts are not specialized or restricted in audience.",
            "Length does not establish whether knowledge is esoteric.",
        ),
        example="The footnote addressed an esoteric dispute among textual scholars.",
        synonyms="specialized, arcane, obscure",
        nuance="Esoteric need not mean secret; the audience may simply need specialist knowledge.",
        alternatives=(
            "ubiquitous",
            "laconic",
        ),
    ),
    VocabWord(
        id=26,
        word="prescient",
        pos="adjective",
        definition="Showing apparent knowledge of events before they happen.",
        difficulty="Advanced",
        prompt="An economist anticipates a change.",
        options=(
            "Her prescient warning described the crisis months before it unfolded.",
            "Her prescient warning merely recounted the crisis years afterward.",
            "Prescient meant she could explain only past events.",
            "Her warning was prescient because it was beautifully printed.",
        ),
        reasons=(
            "Accurate anticipation of a future event illustrates prescience.",
            "Retrospective reporting is not foreknowledge.",
            "Explaining only the past does not show anticipation.",
            "Presentation quality does not establish foresight.",
        ),
        example="The novel's prescient depiction of surveillance now feels familiar.",
        synonyms="farseeing, prophetic",
        nuance="Prescient describes foresight; it does not require supernatural prediction.",
        alternatives=(),
    ),
    VocabWord(
        id=27,
        word="inchoate",
        pos="adjective",
        definition="Just beginning and not yet fully formed or organized.",
        difficulty="Advanced",
        prompt="An idea is taking shape.",
        options=(
            "Her inchoate proposal contained a promising instinct but no clear plan yet.",
            "Her inchoate proposal was complete and fully polished.",
            "Inchoate meant that the project was finished years ago.",
            "The proposal was inchoate because its final design was precise.",
        ),
        reasons=(
            "An emerging but unformed proposal is inchoate.",
            "A fully formed proposal is no longer inchoate.",
            "Completion contradicts the beginning stage.",
            "A precise final design is developed rather than unformed.",
        ),
        example="An inchoate sense of unease gradually became a specific concern.",
        synonyms="nascent, embryonic",
        nuance="Inchoate emphasizes lack of formation, not merely novelty.",
        alternatives=(),
    ),
    VocabWord(
        id=28,
        word="ameliorate",
        pos="verb",
        definition="Improve a bad or unsatisfactory situation.",
        difficulty="Advanced",
        prompt="A policy addresses poor living conditions.",
        options=(
            "The reforms can ameliorate conditions by improving access to clean water.",
            "The reforms ameliorated conditions by making them worse.",
            "Ameliorate meant to preserve every existing problem unchanged.",
            "The policy ameliorated conditions simply by describing them.",
        ),
        reasons=(
            "Better access improves the unsatisfactory situation.",
            "Worsening is the opposite of improvement.",
            "Preserving problems does not improve them.",
            "Description alone does not improve conditions.",
        ),
        example="Extra support helped ameliorate the effects of isolation.",
        synonyms="improve, alleviate",
        nuance="Ameliorate is formal and commonly concerns conditions or harmful effects.",
        alternatives=(),
    ),
    VocabWord(
        id=29,
        word="recalcitrant",
        pos="adjective",
        definition="Stubbornly resisting authority, guidance, or control.",
        difficulty="Advanced",
        prompt="A committee refuses an agreed procedure.",
        options=(
            "The recalcitrant members repeatedly refused to follow the agreed rules.",
            "The recalcitrant members complied readily with every instruction.",
            "Recalcitrant meant the members had never received instructions.",
            "The members were recalcitrant because they were very quiet.",
        ),
        reasons=(
            "Persistent refusal illustrates resistance to control.",
            "Ready compliance is the opposite of resistance.",
            "Lack of instructions does not establish defiance.",
            "Quietness alone says nothing about resistance.",
        ),
        example="The trainer struggled with a recalcitrant horse.",
        synonyms="defiant, obstinate",
        nuance="Recalcitrant often involves resistance to authority, not any disagreement.",
        alternatives=(),
    ),
    VocabWord(
        id=30,
        word="perspicacious",
        pos="adjective",
        definition="Quick to notice and understand things that are not obvious.",
        difficulty="Advanced",
        prompt="A reviewer spots a hidden assumption that everyone else has missed.",
        options=(
            "Her perspicacious analysis exposed the assumption beneath the argument.",
            "His perspicacious memory let him recite the report word for word.",
            "The perspicacious speaker persuaded the audience through sheer charisma.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: quick to notice and understand things that are not obvious.",
            "Memory alone does not establish perceptive understanding.",
            "Charisma and persuasion do not necessarily involve insight.",
        ),
        example="The perspicacious editor noticed that the two sources shared the same original error.",
        synonyms="perceptive, astute, discerning",
        nuance="Perspicacious emphasizes penetrating insight; it is more specific than simply intelligent.",
        alternatives=(
            "meticulous",
            "eloquent",
        ),
    ),
    VocabWord(
        id=31,
        word="nuanced",
        pos="adjective",
        definition="Showing or recognizing subtle distinctions.",
        difficulty="Foundation",
        prompt="A critique distinguishes several shades of meaning instead of making a blanket judgment.",
        options=(
            "Her nuanced critique separated the policy's intentions from its uneven results.",
            "His nuanced verdict declared every aspect either perfect or worthless.",
            "The nuanced report used complicated words but ignored all distinctions.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: showing or recognizing subtle distinctions.",
            "A rigid either-or verdict suppresses subtle distinctions.",
            "Complex language does not by itself demonstrate subtle understanding.",
        ),
        example="The review offered a nuanced account of the character's loyalty and resentment.",
        synonyms="subtle, discriminating, fine-grained",
        nuance="Nuanced concerns meaningful distinctions, not vagueness or unnecessary complexity.",
        alternatives=(
            "dogmatic",
            "equivocal",
        ),
    ),
    VocabWord(
        id=32,
        word="alacrity",
        pos="noun",
        definition="Cheerful readiness or eagerness.",
        difficulty="Advanced",
        prompt="A volunteer eagerly accepts an unexpected assignment.",
        options=(
            "She accepted the assignment with alacrity and immediately offered to help further.",
            "He accepted with alacrity only after repeated pressure, visibly reluctant.",
            "The work showed alacrity because every measurement was exact.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: cheerful readiness or eagerness.",
            "Visible reluctance contradicts eager willingness.",
            "Exactness is precision, not cheerful readiness.",
        ),
        example="The team responded with alacrity to the chance to test its idea.",
        synonyms="eagerness, enthusiasm, readiness",
        nuance="Alacrity often describes willingness to act; speed without willingness is insufficient.",
        alternatives=(
            "reticence",
            "precision",
        ),
    ),
    VocabWord(
        id=33,
        word="specious",
        pos="adjective",
        definition="Appearing sound or plausible but actually misleading or false.",
        difficulty="Advanced",
        prompt="An argument initially looks convincing, but scrutiny exposes its flawed premise.",
        options=(
            "The specious argument looked persuasive until its false premise was exposed.",
            "Her specious argument survived every challenge because its premises and reasoning were sound.",
            "The specious argument was obviously absurd to everyone from the first sentence.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: appearing sound or plausible but actually misleading or false.",
            "Sound premises and valid reasoning do not support calling an argument specious.",
            "Specious implies a misleading appearance of plausibility, not obvious absurdity.",
        ),
        example="The advertisement made a specious comparison between two unrelated statistics.",
        synonyms="misleading, fallacious, deceptive",
        nuance="Specious criticizes apparent validity; it does not merely mean speculative.",
        alternatives=(
            "cogent",
            "tenuous",
        ),
    ),
    VocabWord(
        id=34,
        word="intransigent",
        pos="adjective",
        definition="Unwilling to change a position or compromise.",
        difficulty="Advanced",
        prompt="A negotiator refuses every compromise despite mounting costs.",
        options=(
            "The intransigent negotiator rejected every concession and refused to revise her demands.",
            "The intransigent negotiator readily revised her demands to reach a compromise.",
            "His intransigent argument was difficult to understand because it used unfamiliar terminology.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: unwilling to change a position or compromise.",
            "Readiness to compromise conflicts with intransigence.",
            "Unfamiliar terminology makes language difficult, not a person uncompromising.",
        ),
        example="The board's intransigent stance left little room for negotiation.",
        synonyms="unyielding, uncompromising, obstinate",
        nuance="Intransigent is stronger than firm and usually implies a refusal that blocks agreement.",
        alternatives=(
            "pragmatic",
            "esoteric",
        ),
    ),
    VocabWord(
        id=35,
        word="elucidate",
        pos="verb",
        definition="Make something clear by explaining it.",
        difficulty="Intermediate",
        prompt="A tutor explains a difficult argument step by step.",
        options=(
            "The tutor used a diagram to elucidate the relationship between the variables.",
            "The tutor elucidated the confusion by making it more severe.",
            "She elucidated the passage by deleting it without explanation.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: make something clear by explaining it.",
            "Increasing confusion obscures rather than clarifies.",
            "Removing a passage does not explain its meaning.",
        ),
        example="The appendix elucidates the assumptions behind the model.",
        synonyms="clarify, explain, illuminate",
        nuance="Elucidate concerns understanding; it does not mean approve or resolve every problem.",
        alternatives=(
            "mitigate",
            "obfuscate",
        ),
    ),
    VocabWord(
        id=36,
        word="obfuscate",
        pos="verb",
        definition="Make something obscure or difficult to understand.",
        difficulty="Advanced",
        prompt="A spokesperson hides a simple issue beneath confusing jargon.",
        options=(
            "The spokesperson used technical jargon to obfuscate the simple question.",
            "The guide obfuscated the issue by explaining it clearly in plain language.",
            "The contractor obfuscated the leak by repairing the broken pipe.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: make something obscure or difficult to understand.",
            "Plain explanation clarifies, the opposite of obfuscation.",
            "Repairing a physical problem is not making its meaning obscure.",
        ),
        example="The unnecessary acronyms obfuscated an otherwise straightforward policy.",
        synonyms="obscure, confuse, cloud",
        nuance="Obfuscate often implies deliberate obscuring, though intent depends on context.",
        alternatives=(
            "elucidate",
            "mitigate",
        ),
    ),
    VocabWord(
        id=37,
        word="exacerbate",
        pos="verb",
        definition="Make a problem or negative condition worse.",
        difficulty="Intermediate",
        prompt="A hasty response increases existing tension.",
        options=(
            "An accusatory email can exacerbate the tension between the departments.",
            "The careful apology exacerbated the tension by reducing it.",
            "The analyst exacerbated the tension by describing it accurately, without affecting it.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: make a problem or negative condition worse.",
            "Reducing a problem alleviates or mitigates it.",
            "Describing a condition does not necessarily worsen it.",
        ),
        example="The dry wind exacerbated the risk of fire.",
        synonyms="aggravate, worsen, intensify",
        nuance="Exacerbate normally refers to adverse conditions, not improvements.",
        alternatives=(
            "mitigate",
            "elucidate",
        ),
    ),
    VocabWord(
        id=38,
        word="disparate",
        pos="adjective",
        definition="Essentially different in kind or difficult to compare.",
        difficulty="Intermediate",
        prompt="A study tries to compare groups with very different backgrounds.",
        options=(
            "The report combined data from disparate populations with markedly different circumstances.",
            "The disparate populations were identical in every relevant respect.",
            "The populations were disparate only because they were separated by a locked door.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: essentially different in kind or difficult to compare.",
            "Identical groups are not essentially different.",
            "Physical separation alone does not establish a difference in kind.",
        ),
        example="The festival brought together disparate musical traditions.",
        synonyms="dissimilar, divergent, distinct",
        nuance="Disparate emphasizes difference in character, not merely distance or separation.",
        alternatives=(
            "analogous",
            "ubiquitous",
        ),
    ),
    VocabWord(
        id=39,
        word="analogous",
        pos="adjective",
        definition="Comparable in certain respects, often to help explain something.",
        difficulty="Intermediate",
        prompt="A writer compares two systems because they share a useful structural similarity.",
        options=(
            "She described an analogous process in biology to explain the feedback loop in economics.",
            "The systems were analogous because they had nothing relevant in common.",
            "The two words were analogous simply because they rhymed.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: comparable in certain respects, often to help explain something.",
            "Analogy requires a meaningful similarity.",
            "A shared sound alone does not establish a useful comparison of meaning or structure.",
        ),
        example="The court considered an analogous case with a similar contractual dispute.",
        synonyms="comparable, similar, parallel",
        nuance="Analogous does not mean identical; an analogy can illuminate while still having limits.",
        alternatives=(
            "disparate",
            "equivocal",
        ),
    ),
    VocabWord(
        id=40,
        word="judicious",
        pos="adjective",
        definition="Showing sound judgment and careful consideration.",
        difficulty="Intermediate",
        prompt="A manager weighs the trade-offs before deciding how to spend a limited budget.",
        options=(
            "Her judicious allocation balanced urgent repairs against long-term needs.",
            "His judicious decision ignored all the evidence and followed a sudden impulse.",
            "The allocation was judicious because it was made by a judge, regardless of its wisdom.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: showing sound judgment and careful consideration.",
            "Ignoring evidence and acting impulsively does not show careful judgment.",
            "Judicious concerns wisdom, not the profession of the decision-maker.",
        ),
        example="Judicious pruning improved the essay without losing its central argument.",
        synonyms="wise, considered, prudent",
        nuance="Judicious describes thoughtful choice, often in how something is used or allocated.",
        alternatives=(
            "arbitrary",
            "intransigent",
        ),
    ),
    VocabWord(
        id=41,
        word="arbitrary",
        pos="adjective",
        definition="Based on whim or an insufficiently justified choice rather than a clear reason.",
        difficulty="Intermediate",
        prompt="A rule sets different limits without explaining why the difference matters.",
        options=(
            "The arbitrary cutoff excluded similar cases without a relevant justification.",
            "The arbitrary cutoff followed directly from a carefully validated safety threshold.",
            "The cutoff was arbitrary because everyone agreed on its well-supported rationale.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: based on whim or an insufficiently justified choice rather than a clear reason.",
            "A validated relevant reason makes the cutoff justified rather than arbitrary.",
            "Agreement alone is not enough, but a well-supported rationale contradicts the intended meaning.",
        ),
        example="The policy imposed an arbitrary fee unrelated to the cost of the service.",
        synonyms="capricious, unreasoned, random",
        nuance="Arbitrary need not mean statistically random; a deliberate decision can still lack justification.",
        alternatives=(
            "judicious",
            "pragmatic",
        ),
    ),
    VocabWord(
        id=42,
        word="auspicious",
        pos="adjective",
        definition="Suggesting favorable prospects or a promising outcome.",
        difficulty="Advanced",
        prompt="An early success suggests that a new collaboration may go well.",
        options=(
            "The successful first trial was an auspicious beginning for the collaboration.",
            "The auspicious beginning provided compelling evidence that failure was inevitable.",
            "The beginning was auspicious because its exact date was unknown.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: suggesting favorable prospects or a promising outcome.",
            "Evidence of inevitable failure is unfavorable, not promising.",
            "An unknown date says nothing about favorable prospects.",
        ),
        example="Clear weather made an auspicious start to the expedition.",
        synonyms="promising, favorable, propitious",
        nuance="Auspicious signals favorable indications, not a guarantee of success.",
        alternatives=(
            "tenuous",
            "equivocal",
        ),
    ),
    VocabWord(
        id=43,
        word="resilient",
        pos="adjective",
        definition="Able to recover or adapt after difficulty or strain.",
        difficulty="Foundation",
        prompt="A community rebuilds and adapts after a damaging setback.",
        options=(
            "The resilient community rebuilt its services after the storm.",
            "The resilient community never encountered any challenge, so its capacity to recover was demonstrated.",
            "The resilient plan resisted every change even when conditions demanded adaptation.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: able to recover or adapt after difficulty or strain.",
            "Without a challenge, this sentence does not demonstrate recovery capacity.",
            "Rigid resistance to necessary adaptation is not resilience.",
        ),
        example="The resilient team learned from the failed launch and tried a revised approach.",
        synonyms="adaptable, robust, hardy",
        nuance="Resilience means recovering or adapting; it does not require being untouched by harm.",
        alternatives=(
            "intransigent",
            "sanguine",
        ),
    ),
    VocabWord(
        id=44,
        word="latent",
        pos="adjective",
        definition="Present but not yet visible, active, or developed.",
        difficulty="Intermediate",
        prompt="An ability exists but has not yet had a chance to emerge.",
        options=(
            "The workshop revealed her latent talent for composition.",
            "Her latent talent was already openly displayed in every performance.",
            "The latent talent did not exist in any form until it was created from nothing.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: present but not yet visible, active, or developed.",
            "Something openly manifested is no longer latent in that respect.",
            "Latent implies a present potential, not complete absence.",
        ),
        example="The dispute exposed latent tensions within the organization.",
        synonyms="dormant, hidden, undeveloped",
        nuance="Latent is about potential or inactivity, rather than deliberate concealment alone.",
        alternatives=(
            "salient",
            "ostensible",
        ),
    ),
    VocabWord(
        id=45,
        word="unequivocal",
        pos="adjective",
        definition="Clear and leaving no room for doubt or ambiguity.",
        difficulty="Intermediate",
        prompt="A decision states the committee's position in unmistakable terms.",
        options=(
            "The committee's unequivocal rejection left no doubt about its position.",
            "The unequivocal reply could reasonably be read as either yes or no.",
            "The reply was unequivocal because its author felt both support and opposition.",
        ),
        reasons=(
            "This sentence demonstrates the meaning: clear and leaving no room for doubt or ambiguity.",
            "Two reasonable conflicting interpretations indicate ambiguity.",
            "Mixed feelings are ambivalence, not clarity of expression.",
        ),
        example="She gave unequivocal support to the revised proposal.",
        synonyms="unambiguous, clear, definite",
        nuance="Unequivocal concerns clarity of meaning; a clear statement can still be false.",
        alternatives=(
            "equivocal",
            "ambivalent",
        ),
    ),
)
